In [1]:
import pandas as pd
df = pd.read_csv('chipotle.tsv',delimiter='\t',encoding='utf-8')

In [2]:
#first 10 lines in database
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [3]:
#observation in dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

In [4]:
# observation in dataset
df.shape

(4622, 5)

In [5]:
#What is the number of columns in the dataset?
df.shape[1]

5

In [6]:
#Print the name of all the columns
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [7]:
#How is the dataset indexed?
df.index

RangeIndex(start=0, stop=4622, step=1)

In [8]:
#Which was the most-ordered item
dk = df.groupby('item_name')
dk = dk.sum()
dk

                                       order_id  quantity
item_name
6 Pack Soft Drink                         52322        55
Barbacoa Bowl                             53972        66
Barbacoa Burrito                          74718        91
Barbacoa Crispy Tacos                      5613        12
Barbacoa Salad Bowl                        9708        10
Barbacoa Soft Tacos                       18725        25
Bottled Water                            175944       211
Bowl                                        472         4
Burrito                                    1550         6
Canned Soda                               76396       126
Canned Soft Drink                        304753       351
Carnitas Bowl                             62742        71
Carnitas Burrito                          51652        60
Carnitas Crispy Tacos                      5868         8
Carnitas Salad                             1500         1
Carnitas Salad Bowl                        6693         6
Carnitas Soft Tacos                       37673        40
Chicken Bowl                             713926       761
Chicken Burrito                          497303       591
Chicken Crispy Tacos                      47382        50
Chicken Salad                             10465         9
Chicken Salad Bowl                       117104       123
Chicken Soft Tacos                        98395       120
Chips                                    208004       230
Chips and Fresh Tomato Salsa             100419       130
Chips and Guacamole                      449959       506
Chips and Mild Fresh Tomato Salsa           279         1
Chips and Roasted Chili Corn Salsa        14999        23
Chips and Roasted Chili-Corn Salsa        17462        18
Chips and Tomatillo Green Chili Salsa     41170        45
Chips and Tomatillo Red Chili Salsa       45556        50
Chips and Tomatillo-Green Chili Salsa     21826        33
Chips and Tomatillo-Red Chili Salsa       18344        25
Crispy Tacos                                434         2
Izze                                      10587        20
Nantucket Nectar                          21814        29
Salad                                      1150         2
Side of Chips                             84769       110
Steak Bowl                               193752       221
Steak Burrito                            328437       386
Steak Crispy Tacos                        35818        36
Steak Salad                                2362         4
Steak Salad Bowl                          29590        31
Steak Soft Tacos                          50177        56
Veggie Bowl                               72270        87
Veggie Burrito                            80962        97
Veggie Crispy Tacos                         668         1
Veggie Salad                               7265         6
Veggie Salad Bowl                         17303        18
Veggie Soft Tacos                          5520         8

In [9]:
dk.sort_values('quantity', ascending=False)

                                       order_id  quantity
item_name
Chicken Bowl                             713926       761
Chicken Burrito                          497303       591
Chips and Guacamole                      449959       506
Steak Burrito                            328437       386
Canned Soft Drink                        304753       351
Chips                                    208004       230
Steak Bowl                               193752       221
Bottled Water                            175944       211
Chips and Fresh Tomato Salsa             100419       130
Canned Soda                               76396       126
Chicken Salad Bowl                       117104       123
Chicken Soft Tacos                        98395       120
Side of Chips                             84769       110
Veggie Burrito                            80962        97
Barbacoa Burrito                          74718        91
Veggie Bowl                               72270        87
Carnitas Bowl                             62742        71
Barbacoa Bowl                             53972        66
Carnitas Burrito                          51652        60
Steak Soft Tacos                          50177        56
6 Pack Soft Drink                         52322        55
Chips and Tomatillo Red Chili Salsa       45556        50
Chicken Crispy Tacos                      47382        50
Chips and Tomatillo Green Chili Salsa     41170        45
Carnitas Soft Tacos                       37673        40
Steak Crispy Tacos                        35818        36
Chips and Tomatillo-Green Chili Salsa     21826        33
Steak Salad Bowl                          29590        31
Nantucket Nectar                          21814        29
Chips and Tomatillo-Red Chili Salsa       18344        25
Barbacoa Soft Tacos                       18725        25
Chips and Roasted Chili Corn Salsa        14999        23
Izze                                      10587        20
Veggie Salad Bowl                         17303        18
Chips and Roasted Chili-Corn Salsa        17462        18
Barbacoa Crispy Tacos                      5613        12
Barbacoa Salad Bowl                        9708        10
Chicken Salad                             10465         9
Carnitas Crispy Tacos                      5868         8
Veggie Soft Tacos                          5520         8
Burrito                                    1550         6
Veggie Salad                               7265         6
Carnitas Salad Bowl                        6693         6
Bowl                                        472         4
Steak Salad                                2362         4
Salad                                      1150         2
Crispy Tacos                                434         2
Chips and Mild Fresh Tomato Salsa           279         1
Carnitas Salad                             1500         1
Veggie Crispy Tacos                         668         1

In [10]:
#What was the most ordered item in the choice_description column
df.head(20)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,7,1,Chips and Guacamole,NaN,$4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
18,9,2,Canned Soda,[Sprite],$2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75

In [11]:
dn = df.groupby('choice_description')
dn = dn.sum()
dn

                                                    order_id  quantity
choice_description
[Adobo-Marinated and Grilled Chicken, Pinto Bea...       214         1
[Adobo-Marinated and Grilled Chicken, [Sour Cre...       279         1
[Adobo-Marinated and Grilled Chicken]                    217         1
[Adobo-Marinated and Grilled Steak, [Sour Cream...       279         1
[Adobo-Marinated and Grilled Steak]                      217         1
[Apple]                                                 3966         6
[Blackberry]                                            5220         8
[Braised Barbacoa, Pinto Beans, [Sour Cream, Sa...       217         1
[Braised Barbacoa, Vegetarian Black Beans, [Sou...       214         1
[Braised Carnitas, Pinto Beans, [Sour Cream, Ch...       193         3
[Brown Rice, Adobo-Marinated and Grilled Chicke...       575         1
[Brown Rice]                                            1793         1
[Clementine]                                            4777         8
[Coca Cola]                                            19282        32
[Coke]                                                122752       143
[Diet Coke]                                           123455       159
[Diet Dr. Pepper]                                      10405        14
[Dr. Pepper]                                           13223        21
[Fresh Tomato (Mild), [Black Beans, Guacamole, ...      1252         1
[Fresh Tomato (Mild), [Black Beans, Rice, Sour ...      3128         2
[Fresh Tomato (Mild), [Guacamole, Lettuce, Pint...       868         2
[Fresh Tomato (Mild), [Guacamole, Lettuce, Rice...       453         1
[Fresh Tomato (Mild), [Guacamole, Lettuce, Rice...       204         1
[Fresh Tomato (Mild), [Guacamole, Lettuce, Rice...       527         1
[Fresh Tomato (Mild), [Guacamole, Rice, Black B...       666         1
[Fresh Tomato (Mild), [Guacamole, Rice, Fajita ...       479         1
[Fresh Tomato (Mild), [Guacamole, Rice, Sour Cr...      1415         1
[Fresh Tomato (Mild), [Guacamole, Rice]]                1160         1
[Fresh Tomato (Mild), [Guacamole, Sour Cream, C...      1041         2
[Fresh Tomato (Mild), [Lettuce, Black Beans, Gu...      1146         1
...                                                      ...       ...
[[Tomatillo-Green Chili Salsa (Medium), Roasted...      8150         6
[[Tomatillo-Green Chili Salsa (Medium), Roasted...       538         1
[[Tomatillo-Green Chili Salsa (Medium), Roasted...      1607         2
[[Tomatillo-Green Chili Salsa (Medium), Roasted...       202         1
[[Tomatillo-Green Chili Salsa (Medium), Roasted...       439         1
[[Tomatillo-Green Chili Salsa (Medium), Roasted...       424         1
[[Tomatillo-Green Chili Salsa (Medium), Roasted...      1025         1
[[Tomatillo-Green Chili Salsa (Medium), Roasted...      1284         2
[[Tomatillo-Green Chili Salsa (Medium), Roasted...        14         1
[[Tomatillo-Green Chili Salsa (Medium), Roasted...       871         1
[[Tomatillo-Green Chili Salsa (Medium), Roasted...       992         2
[[Tomatillo-Green Chili Salsa (Medium), Roasted...      2129         2
[[Tomatillo-Green Chili Salsa (Medium), Tomatil...       667         1
[[Tomatillo-Green Chili Salsa (Medium), Tomatil...       435         1
[[Tomatillo-Green Chili Salsa (Medium), Tomatil...       513         2
[[Tomatillo-Green Chili Salsa (Medium), Tomatil...        12         1
[[Tomatillo-Green Chili Salsa (Medium), Tomatil...      1470         1
[[Tomatillo-Green Chili Salsa (Medium), Tomatil...      1002         1
[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomato...       108         1
[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomato...       988         1
[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomato...        76         1
[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomato...      1338         1
[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomato...       579         1
[[Tomatillo-Red Chili Salsa (Hot), Fresh Tomato...      1010         1
[[Tomatillo-Red Chili Salsa (Hot), Roasted Chil...       186         1
[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Gr...      2576         2
[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Gr...      1215         1
[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Gr...        51         1
[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Gr...        51         1
[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Gr...      1299         1

[1043 rows x 2 columns]

In [13]:
#How many items were orderd in total?
df.quantity.sum()

4972

In [14]:
#Turn the item price into a float
df.item_price

0        $2.39
1        $3.39
2        $3.39
3        $2.39
4       $16.98
5       $10.98
6        $1.69
7       $11.75
8        $9.25
9        $9.25
10       $4.45
11       $8.75
12       $8.75
13      $11.25
14       $4.45
15       $2.39
16       $8.49
17       $8.49
18       $2.18
19       $8.75
20       $4.45
21       $8.99
22       $3.39
23      $10.98
24       $3.39
25       $2.39
26       $8.49
27       $8.99
28       $1.09
29       $8.49
         ...
4592    $11.75
4593    $11.75
4594    $11.75
4595     $8.75
4596     $4.45
4597     $1.25
4598     $1.50
4599     $8.75
4600     $4.45
4601     $1.25
4602     $9.25
4603     $9.25
4604     $8.75
4605     $4.45
4606     $1.25
4607    $11.75
4608    $11.25
4609     $1.25
4610    $11.75
4611    $11.25
4612     $9.25
4613     $2.15
4614     $1.50
4615     $8.75
4616     $4.45
4617    $11.75
4618    $11.75
4619    $11.25
4620     $8.75
4621     $8.75
Name: item_price, Length: 4622, dtype: object